name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', truffleruby-head ]

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@f0971f0dd45a5cbb3f119f7db77cc58057c53530
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        find ./spec/fixtures -type f -exec chmod 600 -- {} +
        bundle exec rspec
